import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import { Footer } from '@/components/common/Footer';
import { Box } from '@mui/material';
import { InquiryBlock } from '@/components/common/InquiryBlock';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja' >
      <body className={inter.className}>
        <Box mt={'3%'}>
          {children}
          <InquiryBlock />
        </Box>
        <Box mt={10}>
          <Footer />
        </Box>
      </body>
    </html>
  );
}
